[package]
name = "state-reconstruct"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.73"
clap = { version = "4.4.0", features = ["derive"] }
ethers = "1"
eyre = "0.6.8"
hex = "0.4.3"
indexmap = { version = "2.0.1", features = ["serde"] }
rand = "0.8.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
thiserror = "1.0"
tokio = { version = "1.32.0", features = ["macros"] }
zk_evm = { git = "https://github.com/matter-labs/era-zk_evm.git" }
zksync_merkle_tree = { git = "https://github.com/matter-labs/zksync-era.git" }
