[package]
name = "state-reconstruct"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.0"
ethers = "2.0.10"
eyre = "0.6.8"
serde_json = "1.0.107"
thiserror = "1.0"
tokio = { version = "1.32.0", features = ["macros"] }
