name: basics

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        checks: [
          fmt --all --check,
          check --all-targets --all-features,
          clippy --all-targets --all-features,
          test
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install nightly Rust
        run: rustup default nightly
      - name: ${{ matrix.checks }}
        run: cargo ${{ matrix.checks }}
